version: '3'

services:

  air-quality-front:
    build:
      context: .
    container_name: quality_air_frontend
    ports:
      - "80:80"
    depends_on:
      - keycloak
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    restart: always
    volumes:
      - ./keycloak_init.json:/opt/keycloak/data/import/keycloak_init.json
    command: ["start-dev", "--import-realm"]

volumes:
  dbdata: 
    driver: local