version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8092:80"

  air-quality-back:
    build:
      context: ./backend 
    container_name: quality_air_backend
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/air_quality
      - spring.datasource.username=root
      - spring.datasource.password=root

  air-quality-front:
    build:
      context: .
    container_name: quality_air_frontend
    ports:
      - "80:80"

volumes:
  dbdata: 
    driver: local